### PR TITLE
OCT-1284 Create an IPFS implementation with client failover

### PR DESCRIPTION
**Pull request by aziolek**

### CODE REVIEW

**Comment by aziolek** [comment]
@jmikolajczyk: to test it, please set the local environmental variable `VITE_IPFS_GATEWAYS=https://octant.infura-ipfs.io/ipfs/,https://turquoise-accused-gayal-88.mypinata.cloud/ipfs/`.

**Review by aziolek — COMMENTED** [review]
- [ ] Before the production release: add a new environmental variable:
```
VITE_IPFS_GATEWAYS=https://turquoise-accused-gayal-88.mypinata.cloud/ipfs/,https://octant.infura-ipfs.io/ipfs/
```

**Review by jmikolajczyk — APPROVED** [review]

**Review by mike-code — DISMISSED** [review]
approving per automatic PR destination branch change

**Review by mike-code — DISMISSED** [review]
re-approving after updating argo app

**Review by jmikolajczyk — APPROVED** [review]

**Pull request merged**
