### PR TITLE
Fix math operations on NoneType

### PR DESCRIPTION
**Pull request by mike-code**
## Description

Across the codebase there're math operations (`+ - * /`) performed on properties of the `LeftoverPayload` DTO. Those lead to exceptions as you can't do math operations on type `None`.  

## Definition of Done

1. [ ] Acceptance criteria are met.
2. [ ] PR is manually tested before the merge by developer(s).
    - [ ] Happy path is manually checked.
3. [ ] PR is manually tested by QA when their assistance is required (1).
    - [ ] Octant Areas & Test Cases are checked for impact and updated if required (2).
4. [ ] Unit tests are added unless there is a reason to omit them.
5. [ ] Automated tests are added when required.
6. [ ] The code is merged.
7. [ ] Tech documentation is added / updated, reviewed and approved (including mandatory approval by a code owner, should such exist for changed files).
    - [ ] BE: Swagger documentation is updated.
8. [ ] When required by QA:
    - [ ] Deployed to the relevant environment.
    - [ ] Passed system tests.

---

(1) Developer(s) in coordination with QA decide whether it's required. For small tickets introducing small changes QA assistance is most probably not required.

(2) [Octant Areas & Test Cases](https://docs.google.com/spreadsheets/d/1cRe6dxuKJV3a4ZskAwWEPvrFkQm6rEfyUCYwLTYw_Cc).

### CODE REVIEW

**Comment by kgarbacinski** [comment]
Can you please give any specific places where you observed the problem?

**Comment by mike-code** [comment]
> Can you please give any specific places where you observed the problem?

**LeftoverWithPPFAndUnusedMR**
```
        unused_matched_rewards = (
            payload.total_matched_rewards - payload.used_matched_rewards
        )

```

**Comment by kgarbacinski** [comment]
> > Can you please give any specific places where you observed the problem?
> 
> **LeftoverWithPPFAndUnusedMR**
> 
> ```
>         unused_matched_rewards = (
>             payload.total_matched_rewards - payload.used_matched_rewards
>         )
> ```

Replacing None values with 0 may secure us from throwing NoneType error indeed but I think that we always expect any value put into the fields in the Payload when we use such fields in the calculations. If such field is None, then something unexpected happened in the backend and we need to debug it. Replacing None with 0 will probably protect us from such errors but then the calculations may be not correct (because we something missed and settled the value as 0) and it maybe a way harder to debug IMHO than having just a NoneType error. 

Do you agree?

**Comment by mike-code** [comment]
> > > Can you please give any specific places where you observed the problem?
> > 
> > 
> > **LeftoverWithPPFAndUnusedMR**
> > ```
> >         unused_matched_rewards = (
> >             payload.total_matched_rewards - payload.used_matched_rewards
> >         )
> > ```
> 
> Replacing None values with 0 may secure us from throwing NoneType error indeed but I think that we always expect any value put into the fields in the Payload when we use such fields in the calculations. If such field is None, then something unexpected happened in the backend and we need to debug it. Replacing None with 0 will probably protect us from such errors but then the calculations may be not correct (because we something missed and settled the value as 0) and it maybe a way harder to debug than having just a NoneType error IMHO.
> 
> Do you agree?

I don't know about whether 0 as a default is correct for the calculation purposes or not.

If `None` is never expected then instantiating this object without a value should not be possible in the first place. I'm escalating this to an issue.

**Pull request closed without merging**
