### PR TITLE
api tests: pass args to pytest

### PR DESCRIPTION
**Pull request by paulperegud**
This allows to use usual pytest way of specifying which test should be executed

### CODE REVIEW

**Review by MateuszStoleckiGLM — APPROVED** [review]

**Comment by mike-code** [comment]
Is this one somehow related to https://linear.app/golemfoundation/issue/OCT-1318/add-ci-step-for-backend-api-tests ?

**Comment by paulperegud** [comment]
> Is this one somehow related to https://linear.app/golemfoundation/issue/OCT-1318/add-ci-step-for-backend-api-tests ?

No. This one just enables running single test or all tests from single file. Normal pytest functionality exposed through layers (docker, docker-compose and yarn).

**Comment by paulperegud** [comment]
Blocked by #36

**Comment by leoni-q** [comment]
@paulperegud https://github.com/golemfoundation/octant/pull/36 is merged, you can rebase and re-run

**Review by MateuszStoleckiGLM — DISMISSED** [review]

**Pull request merged**
